pipeline {
    agent any

    environment {
        DOCKER_USER = 'lokesh815'
        IMAGE_BACKEND = "${DOCKER_USER}/mern-backend"
        IMAGE_FRONTEND = "${DOCKER_USER}/mern-frontend"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/loke815/MERN-docker-compose.git'
            }
        }

        stage('Build Backend') {
            steps {
                dir('mern/backend') {
                    sh 'docker build -t lokesh815/mern-backend:latest .'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('mern/frontend') {
                    sh 'docker build -t lokesh815/mern-frontend:latest .'
                }
            }
        }

        stage('Push Images') {
            steps {
                script {
                    docker.withRegistry('', 'dockerhub-creds') {
                        sh 'docker push lokesh815/mern-backend:latest'
                        sh 'docker push lokesh815/mern-frontend:latest'
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
}
